# Based on these extensions 
# https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform
# https://marketplace.visualstudio.com/acquisition?itemName=ms-devlabs.custom-terraform-tasks
# https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-vsts-tools
parameters:
- name: environment
  type: string
  default:
- name: workingdir
  type: string
  default:
- name: connection
  type: string
  default:
- name: options
  type: string
  default:
- name: aws_region
  type: string
  default:


stages:
- stage: plan
  displayName: Plan
  dependsOn:
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: terraform
    displayName: Terraform
    steps:
      - task: TerraformCLI@0
        displayName: Init
        inputs:
          command: init
          workingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.workingdir }}
          allowTelemetryCollection: false
          backendType: aws
          backendServiceAws: ${{ parameters.connection }}
          commandOptions: --upgrade

      - task: TerraformCLI@0
        displayName: Plan
        inputs:
          command: plan
          workingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.workingdir }}
          allowTelemetryCollection: false
          providerServiceAws: ${{ parameters.connection }}
          providerAwsRegion: ${{ parameters.aws_region }}
          commandOptions: -out=tfplan ${{ parameters.options }}

      - task: PowerShell@2
        displayName: Check for changes
        name: tf_changes_present
        inputs:
          targetType: inline
          script: |
            Write-Host "TERRAFORM_PLAN_HAS_CHANGES: $($env:TERRAFORM_PLAN_HAS_CHANGES)"
            Write-Host "TERRAFORM_LAST_EXITCODE: $($env:TERRAFORM_LAST_EXITCODE)"
            Write-Host "##vso[task.setvariable variable=plan_has_changes;isOutput=true]$env:TERRAFORM_PLAN_HAS_CHANGES"

      - task: CopyFiles@2
        displayName: Copy artifacts
        condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)/${{ parameters.workingdir }}
          Contents: |
            **
            !.terraform/**
          TargetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish artifacts
        condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: terraform

#- task: TerraformCLI@0
#  displayName: 'terraform apply'
#  condition: and(succeeded(), eq(variables['TERRAFORM_PLAN_HAS_CHANGES'], 'true'))
#  inputs:
#    command: apply
#    environmentServiceName: 'My Azure Service Connection'
#    commandOptions: '$(System.DefaultWorkingDirectory)/terraform.tfplan'

- stage: apply
  displayName: Apply
  dependsOn: plan
  condition: eq(stageDependencies.plan.outputs['terraform.tf_changes_present.plan_has_changes'], 'true')
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: terraform
    displayName: Terraform
    environment: ${{ parameters.environment }}
    strategy: 
      runOnce:
        deploy:
          steps:
            - task: TerraformCLI@0
              displayName: Init
              inputs:
                command: init
                workingDirectory: $(Pipeline.Workspace)/terraform
                allowTelemetryCollection: false
                backendType: aws
                backendServiceAws: ${{ parameters.connection }}

            - task: TerraformCLI@0
              displayName: Apply
              inputs:
                command: apply
                workingDirectory: $(Pipeline.Workspace)/terraform
                allowTelemetryCollection: false
                providerServiceAws: ${{ parameters.connection }}
                providerAwsRegion: ${{ parameters.aws_region }}
                commandOptions: ${{ parameters.options }}