trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/example/**

resources:
  repositories:
  - repository: templates
    type: github
    name: rbjoergensen/azure-devops-templates
    endpoint: github

stages:
- template: /terraform/main.yml@templates
  parameters:
    environment: test
    workingdir: terraform/example
    connection: aws-callofthevoid
    aws_region: eu-central-1